export const attributeTypeDefMap = new Map<string, string>([
    ["Boolean", "Attributes.BooleanAttribute"],
    ["Customer", "Attributes.LookupAttribute"],
    ["DateTime", "Attributes.DateAttribute"],
    ["Decimal", "Attributes.NumberAttribute"],
    ["Double", "Attributes.NumberAttribute"],
    ["Integer", "Attributes.NumberAttribute"],
    ["Lookup", "Attributes.LookupAttribute"],
    ["Memo", "Attributes.StringAttribute"],
    ["Money", "Attributes.NumberAttribute"],
    ["Owner", "Attributes.LookupAttribute"],
    ["PartyList", "Attributes.LookupAttribute"],
    ["Picklist", "Attributes.OptionSetAttribute"],
    ["State", "Attributes.OptionSetAttribute"],
    ["Status", "Attributes.OptionSetAttribute"],
    ["String", "Attributes.StringAttribute"],
    ["Uniqueidentifier", "Attributes.StringAttribute"],
    ["CalendarRules", "Attributes.Attribute"],
    ["Virtual", "Attributes.Attribute"],
    ["BigInt", "Attributes.NumberAttribute"],
    ["ManagedProperty", "Attributes.Attribute"],
    ["EntityName", "Attributes.Attribute"],
]);
export const controlTypeDefMap = new Map<string, string>([
    ["Boolean", "Controls.StandardControl"],
    ["Customer", "Controls.LookupControl"],
    ["DateTime", "Controls.DateControl"],
    ["Decimal", "Controls.NumberControl"],
    ["Double", "Controls.NumberControl"],
    ["Integer", "Controls.NumberControl"],
    ["Lookup", "Controls.LookupControl"],
    ["Memo", "Controls.StringControl"],
    ["Money", "Controls.NumberControl"],
    ["Owner", "Controls.LookupControl"],
    ["PartyList", "Controls.LookupControl"],
    ["Picklist", "Controls.OptionSetControl"],
    ["State", "Controls.OptionSetControl"],
    ["Status", "Controls.OptionSetControl"],
    ["String", "Controls.StringControl"],
    ["Uniqueidentifier", "Controls.StringControl"],
    ["CalendarRules", "Controls.Control"],
    ["Virtual", "Controls.Control"],
    ["BigInt", "Controls.NumberControl"],
    ["ManagedProperty", "Controls.Control"],
    ["EntityName", "Controls.Control"],
]);